Style/ClassAndModuleChildren:
  Exclude:
    - config/**/*
    - test/**/*

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - db/**/*

Metrics/LineLength:
  Exclude:
    - db/**/*
    - config/initializers/*
    - config/*
    - Guardfile

Metrics/MethodLength:
  Max: 30
  Exclude:
    - db/**/*

