version: '3'
services:
  db:
    # Match what is running in production
    image: postgres:9.4
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/reports
    ports:
      - "3000:3000"
    depends_on:
      - db
