# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: chasingtails_dev
  host: localhost

production:
  host: localhost
  adapter: postgresql
  database: tails_production
  encoding: utf8
  pool: 5
  username: postgres
